name: ItemTracker
version: '1.0'
main: eportela.itemtracker.ItemTracker
api-version: '1.16'
authors: [eportela]
description: plugin to track specific items according to their NBTData
website: https://github.com/empsa1
commands:
  trackItem:
    description: Track an item
    usage: /trackItem